# This file is auto-generated by scripts/generate_tfvars.sh
# DO NOT EDIT MANUALLY

environment      = "vagrant"
metallb_ip_range = "192.168.56.200-192.168.56.220"
ingress_ip       = "192.168.56.200"
vip              = "192.168.56.100"
