#!/bin/bash
# Generate Terraform tfvars from Ansible inventory
#
# Usage:
#   ./generate_tfvars.sh [environment]
#
# Examples:
#   ./generate_tfvars.sh production
#   ./generate_tfvars.sh vagrant

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"

# Determine environment
ENV="${1:-production}"

if [[ "$ENV" != "production" && "$ENV" != "vagrant" ]]; then
	echo "❌ Error: Environment must be 'production' or 'vagrant'"
	echo "Usage: $0 [production|vagrant]"
	exit 1
fi

# Set paths based on environment
if [[ "$ENV" == "production" ]]; then
	INVENTORY_FILE="$PROJECT_ROOT/ansible/inventory/inventory.ini"
	OUTPUT_FILE="$PROJECT_ROOT/terraform/environments/production/terraform.auto.tfvars"
else
	INVENTORY_FILE="$PROJECT_ROOT/ansible/inventory/inventory_vagrant.ini"
	OUTPUT_FILE="$PROJECT_ROOT/terraform/environments/vagrant/terraform.auto.tfvars"
fi

if [[ ! -f "$INVENTORY_FILE" ]]; then
	echo "❌ Error: Inventory file not found: $INVENTORY_FILE"
	exit 1
fi

echo "📋 Reading inventory: $INVENTORY_FILE"

# Extract variables from Ansible inventory
extract_var() {
	local var_name="$1"
	grep "^${var_name}=" "$INVENTORY_FILE" | head -1 | cut -d'=' -f2 | tr -d ' '
}

ENVIRONMENT=$(extract_var "environment")
METALLB_IP_RANGE=$(extract_var "metallb_ip_range")
INGRESS_IP=$(extract_var "ingress_ip")
VIP=$(extract_var "vip")

# Validate extracted variables
if [[ -z "$ENVIRONMENT" || -z "$METALLB_IP_RANGE" || -z "$INGRESS_IP" || -z "$VIP" ]]; then
	echo "❌ Error: Failed to extract required variables from inventory"
	echo "Required variables: environment, metallb_ip_range, ingress_ip, vip"
	exit 1
fi

# Create directory if it doesn't exist
mkdir -p "$(dirname "$OUTPUT_FILE")"

# Generate tfvars file (network config only)
cat >"$OUTPUT_FILE" <<EOF
# This file is auto-generated by scripts/generate_tfvars.sh
# DO NOT EDIT MANUALLY

environment      = "$ENVIRONMENT"
metallb_ip_range = "$METALLB_IP_RANGE"
ingress_ip       = "$INGRESS_IP"
vip              = "$VIP"
EOF

echo "✅ Generated Terraform variables: $OUTPUT_FILE"
echo ""
echo "📝 Contents:"
cat "$OUTPUT_FILE"
echo ""
echo "💡 Next steps:"
echo "   1. Copy terraform.tfvars.example to terraform.tfvars in the environment directory"
echo "   2. Edit terraform.tfvars with your GitHub credentials"
echo "   3. Run: cd terraform/environments/$ENV && terraform apply"
