# This file is auto-generated by scripts/generate_tfvars.sh
# DO NOT EDIT MANUALLY

environment      = "production"
metallb_ip_range = "192.168.1.200-192.168.1.220"
ingress_ip       = "192.168.1.200"
vip              = "192.168.1.100"
